# Generated by Django 5.2.3 on 2025-10-18 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bike", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionImage",
            fields=[
                (
                    "baseimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.baseimage",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("story", "스토리"), ("extra", "추가")], max_length=20
                    ),
                ),
                ("order", models.IntegerField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "신청서 이미지",
                "verbose_name_plural": "신청서 이미지",
                "db_table": "submission_submission_image",
                "ordering": ["purpose", "order", "created_at"],
            },
            bases=("core.baseimage",),
        ),
        migrations.CreateModel(
            name="SubmissionStatusLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("submitted", "접수"),
                            ("in_review", "검토중"),
                            ("approved", "승인"),
                            ("posting", "포스팅중"),
                            ("published", "게시 완료"),
                            ("rejected", "반려"),
                            ("resubmitted", "재신청"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("submitted", "접수"),
                            ("in_review", "검토중"),
                            ("approved", "승인"),
                            ("posting", "포스팅중"),
                            ("published", "게시 완료"),
                            ("rejected", "반려"),
                            ("resubmitted", "재신청"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "신청서 상태 로그",
                "verbose_name_plural": "신청서 상태 로그",
                "db_table": "submission_status_log",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("build_snapshot", models.JSONField(default=dict)),
                ("story_blocks", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("submitted", "접수"),
                            ("in_review", "검토중"),
                            ("approved", "승인"),
                            ("posting", "포스팅중"),
                            ("published", "게시 완료"),
                            ("rejected", "반려"),
                            ("resubmitted", "재신청"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "bike",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="bike.bike",
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="bike.bikebuild",
                    ),
                ),
            ],
            options={
                "verbose_name": "신청서",
                "verbose_name_plural": "신청서",
                "db_table": "submission_submission",
            },
        ),
    ]
