# Generated by Django 5.2.3 on 2025-10-18 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submission", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissionimage",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="submission.submission",
            ),
        ),
        migrations.AddField(
            model_name="submissionstatuslog",
            name="changed_by_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_status_logs",
                to="user.staff",
            ),
        ),
        migrations.AddField(
            model_name="submissionstatuslog",
            name="changed_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_status_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissionstatuslog",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="submission.submission",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submission_status_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["user"], name="submission_user_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["created_at"], name="submission_created_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionimage",
            index=models.Index(
                fields=["submission", "purpose"], name="submission_image_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionstatuslog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("changed_by_staff__isnull", False),
                        ("changed_by_user__isnull", True),
                    ),
                    models.Q(
                        ("changed_by_staff__isnull", True),
                        ("changed_by_user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="submission_log_single_actor",
            ),
        ),
    ]
