# Generated by Django 5.2.3 on 2025-10-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0005_submission_add_extended_fields"),
        ("submission", "0011_remove_submission_message"),
    ]

    operations = []
