# Generated by Django 5.2.3 on 2025-10-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0012_merge_20251011_0044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="category",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="consent_license",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="consent_portrait",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="consent_updates",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="location",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="story_challenges",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="story_inspiration",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="story_summary",
        ),
    ]
