# Generated by Django 5.2.3 on 2025-10-18 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeBuild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("components", models.JSONField(default=dict)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "자전거 빌드",
                "verbose_name_plural": "자전거 빌드",
                "db_table": "bike_build",
            },
        ),
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("frame_name", models.CharField(max_length=120)),
                ("frame_brand", models.CharField(max_length=120)),
                (
                    "frame_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Alloy", "알루미늄"),
                            ("Carbon", "카본"),
                            ("Chromoly", "크로몰리"),
                            ("Steel", "강철"),
                            ("Titanium", "티타늄"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_posted", models.BooleanField(default=False)),
                (
                    "main_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_bikes",
                        to="core.baseimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "자전거",
                "verbose_name_plural": "자전거",
                "db_table": "bike_bike",
            },
        ),
    ]
