# Generated by Django 5.2.3 on 2025-10-18 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bike", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bikebuild",
            name="base_bike",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builds",
                to="bike.bike",
            ),
        ),
        migrations.AddIndex(
            model_name="bike",
            index=models.Index(fields=["frame_brand"], name="bike_frame_brand_idx"),
        ),
        migrations.AddIndex(
            model_name="bike",
            index=models.Index(fields=["frame_type"], name="bike_frame_type_idx"),
        ),
        migrations.AddIndex(
            model_name="bike",
            index=models.Index(fields=["is_public"], name="bike_public_idx"),
        ),
        migrations.AddIndex(
            model_name="bike",
            index=models.Index(fields=["is_posted"], name="bike_posted_idx"),
        ),
        migrations.AddIndex(
            model_name="bikebuild",
            index=models.Index(fields=["base_bike"], name="bike_build_base_idx"),
        ),
    ]
