# Generated by Django 5.2.3 on 2025-10-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikebuild",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
