# Generated by Django 5.2.3 on 2025-10-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0003_bikebuild_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikebuild",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
