# Generated by Django 5.2.3 on 2025-10-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0004_alter_bikebuild_is_public"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bike",
            name="bike_frame_brand_idx",
        ),
        migrations.RemoveIndex(
            model_name="bike",
            name="bike_frame_type_idx",
        ),
        migrations.RemoveField(
            model_name="bike",
            name="frame_brand",
        ),
        migrations.RemoveField(
            model_name="bike",
            name="frame_type",
        ),
    ]
