# Generated by Django 5.2.3 on 2025-11-30 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0005_remove_bike_bike_frame_brand_idx_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikebuild",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="build_main_images",
                to="core.baseimage",
            ),
        ),
        migrations.CreateModel(
            name="BuildImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="bike.bikebuild",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_images",
                        to="core.baseimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "빌드 이미지",
                "verbose_name_plural": "빌드 이미지",
                "db_table": "bike_build_image",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(fields=["build", "order"], name="bike_build_image_idx")
                ],
            },
        ),
    ]
