# Generated by Django 5.2.3 on 2025-12-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0006_bikebuild_main_image_buildimage"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bike",
            name="bike_public_idx",
        ),
        migrations.RemoveField(
            model_name="bike",
            name="is_public",
        ),
    ]
