# Generated by Django 5.2.3 on 2026-02-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0008_bikebuildlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildimage",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frame_setup", "Frame Setup"),
                    ("wheel", "Wheel"),
                    ("cockpit", "Cockpit"),
                    ("drivetrain", "Drivetrain"),
                    ("seat", "Seat"),
                    ("brake", "Brake"),
                    ("etc", "Etc"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
