# Generated by Django 5.2.3 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_username_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="riding_since",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
