# Generated by Django 5.2.3 on 2026-02-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_nickname_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_username_public",
        ),
    ]
