# Generated by Django 5.2.3 on 2025-10-18 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글",
                "db_table": "post_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "좋아요",
                "verbose_name_plural": "좋아요",
                "db_table": "post_like",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("build_snapshot", models.JSONField(default=dict)),
                ("main_title", models.CharField(max_length=200)),
                ("sub_title", models.CharField(max_length=200)),
                ("content_md", models.TextField(blank=True)),
                ("content_html", models.TextField()),
                ("content_json", models.JSONField()),
                ("frame_brand", models.CharField(max_length=120)),
                (
                    "frame_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Alloy", "알루미늄"),
                            ("Carbon", "카본"),
                            ("Chromoly", "크로몰리"),
                            ("Steel", "강철"),
                            ("Titanium", "티타늄"),
                        ],
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("review", "검토중"),
                            ("published", "발행"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글",
                "db_table": "post_post",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "baseimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.baseimage",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("thumbnail", "썸네일"),
                            ("header", "헤더"),
                            ("hero", "히어로"),
                            ("body", "본문"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("caption", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "게시글 이미지",
                "verbose_name_plural": "게시글 이미지",
                "db_table": "post_post_image",
                "ordering": ["purpose", "order", "created_at"],
            },
            bases=("core.baseimage",),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그",
                "db_table": "post_tag",
                "ordering": ["name"],
            },
        ),
    ]
