# Generated by Django 5.2.3 on 2025-10-18 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bike", "0002_initial"),
        ("post", "0001_initial"),
        ("submission", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="user.staff",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="bike",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="bike.bike",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="build",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="bike.bikebuild",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="submission",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post",
                to="submission.submission",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="post.post",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="post.post",
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="post.post",
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="source_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_images",
                to="submission.submissionimage",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="post_tag_name_idx"),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="post.tag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "user")},
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(
                fields=["post", "purpose"], name="post_image_post_purpose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="post_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["frame_brand"], name="post_frame_brand_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["frame_type"], name="post_frame_type_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="post_status_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["published_at"], name="post_published_at_idx"),
        ),
    ]
