# Generated by Django 5.2.6 on 2025-09-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_like_post_like_unique_and_more"),
        ("post", "0004_move_submission_to_submission_app"),
    ]

    operations = []
