# Generated by Django 5.2.3 on 2026-01-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_is_editor_pick"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rider_snapshot",
            field=models.JSONField(default=dict),
        ),
    ]
