# Generated by Django 5.2.3 on 2026-02-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_post_rider_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="sub_title",
        ),
    ]
